- name: Install NGINX on all VMs
  hosts: azure_vms
  become: yes
  vars:
    domain_name: cdn.kunals.me
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Create a new contents directory
      file:
        path: /home/custom-cdn/contents
        state: directory
        mode: "0755"
        owner: custom-cdn
        group: custom-cdn

    - name: Install NGINX
      apt:
        name: nginx
        state: latest
      
    - name: Set user in nginx.conf
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^user'
        line: 'user custom-cdn;'
        backrefs: yes
      notify:
        - Restart NGINX

    - name: Create NGINX configuration for new domain
      template:
        src: nginx.conf
        dest: /etc/nginx/sites-available/{{ domain_name }}.conf
      notify:
        - Restart NGINX

    - name: Enable new NGINX site
      file:
        src: /etc/nginx/sites-available/{{ domain_name }}.conf
        dest: /etc/nginx/sites-enabled/{{ domain_name }}.conf
        state: link
      notify:
        - Restart NGINX
        - Reload NGINX

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

    - name: Reload NGINX
      service:
        name: nginx
        state: reloaded